name: seller
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4
  image_picker: ^1.0.7
  provider: ^6.1.1
  location: ^5.0.3
  geolocator: ^11.0.0
  flutter_geocoder: ^0.2.2-nullsafety
  email_validator: ^2.1.17
  firebase_storage: ^11.6.6
  flutter_slider_drawer: ^2.1.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.1
  shimmer_animation: ^2.1.0+1
  modal_progress_hud_nsn: ^0.5.1
  intl: ^0.19.0
  chips_choice: ^3.0.1
  url_launcher: ^6.2.5
  map_launcher: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/images/

